# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit AI Configuration
# https://docs.coderabbit.ai/guides/review-instructions/

reviews:
  profile: assertive
  high_level_summary: true
  # Exclude paths from review
  path_filters:
    - "!8.0/**"
    - "!8.1/**"
    - "!8.2/**"
    - "!8.3/**"
    - "!8.4/**"
    - "!8.5/**"
