name: Verify Templating

on:
  pull_request

# Ensure existing runs are cancelled automatically if still in progress when a
# new one commit is pushed to this pull request. This is scoped to the branch
# and workflow name so that we can run multiple workflows on a branch but
# ensure they're exclusive with regards to concurrency.
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  apply-templates:
    name: Check For Uncomitted Changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Apply Templates
        run: ./apply-templates.sh
      - name: Check Git Status
        run: |
          status="$(git status --short)"
          [ -z "$status" ]
